// Redux Global Action names

// APP
export const APP_LOAD_USER_LOGIN = 'APP_LOAD_USER_LOGIN'; 
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'; 
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'; 
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'; 
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'; 

// THREAT
export const THREATS_LOAD = 'THREATS_LOAD';
export const THREATS_LOAD_REQUEST = 'THREATS_LOAD_REQUEST';
export const THREATS_LOAD_SUCCESS = 'THREATS_LOAD_SUCCESS';
export const THREATS_LOAD_ERROR = 'THREATS_LOAD_ERROR';

export const THREAT_CREATE = 'THREAT_CREATE';
export const THREAT_CREATE_REQUEST = 'THREAT_CREATE_REQUEST';
export const THREAT_CREATE_SUCCESS = 'THREAT_CREATE_SUCCESS';
export const THREAT_CREATE_ERROR = 'THREAT_CREATE_ERROR';

export const THREAT_DELETE = 'THREAT_DELETE';
export const THREAT_DELETE_REQUEST = 'THREAT_DELETE_REQUEST';
export const THREAT_DELETE_SUCCESS = 'THREAT_DELETE_SUCCESS';
export const THREAT_DELETE_ERROR = 'THREAT_DELETE_ERROR';

export const THREAT_UPDATE = 'THREAT_UPDATE';
export const THREAT_UPDATE_REQUEST = 'THREAT_UPDATE_REQUEST';
export const THREAT_UPDATE_SUCCESS = 'THREAT_UPDATE_SUCCESS';
export const THREAT_UPDATE_ERROR = 'THREAT_UPDATE_ERROR';
